language: r
r: 
  - release
os: linux
dist: xenial
cache:
 packages: true
 directories:
  - openmpi-4.0.3   # cache OpenMPI
  
repos:
  CRAN: https://cloud.r-project.org

# Install OpenMPI
before_install:
 #- sh ./get_openmpi.sh 
 - sudo apt-get -y install openmpi-bin libopenmpi-dev
 - sudo apt-get -y install libmagick++-dev

r_packages:
  - covr
  - DiagrammeR

after_success:
  - Rscript -e 'library(covr); codecov()'