language: r
os: linux
dist: xenial
cache:
 packages: true
 directories:
  - openmpi-4.0.3   # cache OpenMPI

# Build OpenMPI
before_install:
 #- sh ./get_openmpi.sh 
 - sudo apt-get -y install openmpi-bin libopenmpi-dev
  
repos:
  CRAN: https://cloud.r-project.org