language: r
os: linux
dist: xenial
cache:
 packages: true
 directories:
  - openmpi-4.0.3   # cache OpenMPI

# Build OpenMPI
before_install:
 - sh ./get_openmpi.sh 
  
repos:
  CRAN: https://cloud.r-project.org